# Generated by Django 5.0.3 on 2024-03-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_members"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
    ]
